const API_BASE_URL = 'http://192.168.0.16:8190/league';

const MATCH_ENDPOINT = '/match';
const MATCH_ACTIVE_ENDPOINT = '/active';
const MATCH_DETAILS_ENDPOINT = '/details';

export const MATCH_ACTIVE_API_URL = API_BASE_URL + MATCH_ENDPOINT + MATCH_ACTIVE_ENDPOINT;

export const MATCH_DETAILS_API_URL = API_BASE_URL + MATCH_ENDPOINT + MATCH_DETAILS_ENDPOINT;